version: '3'
services:
  # Main application container:
  app:
    container_name: flask_app
    restart: unless-stopped
    volumes:
      - flask-secret:/secret/
    build:
      context: .
      dockerfile: Docker/CubeServer-app/Dockerfile
    environment:
      # MongoDB credentials:
      - MONGODB_DATABASE=flaskdb
      - MONGODB_USERNAME=flask
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_PASSWORD=LXUa2AYh5ArNkLkEZC8TCkCfKjE2nYVejvrTcPT82J6dRpJtmnEm6JhWsBnuGJWL
    ports: # Bind the port for the web server
      - "8080:80"
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
  # API server container:
  api:
    container_name: flask_api
    restart: unless-stopped
    volumes:
      - flask-secret:/secret/
    build:
      context: .
      dockerfile: Docker/CubeServer-api/Dockerfile
    environment:
      # MongoDB credentials:
      - MONGODB_DATABASE=flaskdb
      - MONGODB_USERNAME=flask
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_PASSWORD=LXUa2AYh5ArNkLkEZC8TCkCfKjE2nYVejvrTcPT82J6dRpJtmnEm6JhWsBnuGJWL
    ports: # Bind the port for the web server
      - "8081:80"
    depends_on:
      - mongodb
    networks:
      - api
      - backend
  # Database container:
  mongodb:
    container_name: cube_mongodb
    image: mongo:5.0
    volumes: # Corresponds with volume at the bottom
      - mongodb-data:/data/db
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: flask
      MONGO_INITDB_ROOT_PASSWORD: LXUa2AYh5ArNkLkEZC8TCkCfKjE2nYVejvrTcPT82J6dRpJtmnEm6JhWsBnuGJWL
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  api:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  flask-secret:
    driver: local
