version: '3.8'

services:
  combined:
    container_name: ${PROJECT_NAME}-combined
    restart: unless-stopped
    volumes:
      - ../..:/workspaces:cached
      - ./secret_key.txt:/secret/secret_key.txt:cached
      - ../src/CubeServer-common/cubeserver_common:/code/cubeserver_common:cached
      - ../src/CubeServer-common/requirements.txt:/code/requirements-common.txt:cached
      - ../src/CubeServer-api/cubeserver_api:/code/cubeserver_api:cached
      - ../src/CubeServer-api/requirements.txt:/code/requirements-api.txt:cached
      - ./requirements-dev.txt:/code/requirements-dev.txt:cached
      - ../src/CubeServer-app/cubeserver_app:/code/cubeserver_app:cached
      - ../src/CubeServer-app/requirements.txt:/code/requirements-app.txt:cached
      - ./api-server:/code/api-server:cached
      - ./app-server:/code/app-server:cached
      - ./run-tests:/code/run-tests:cached
      - ../Docker/CubeServer/CubeServer-app/package_internal.sh:/code/package_internal.sh:cached
      - ../Docker/CubeServer/CubeServer-app/package_lib.sh:/code/package_lib.sh:cached
    tmpfs:
      - /code/.pytest_cache
    build:
      context: ..
      dockerfile: Docker/CubeServer/Dockerfile
      target: dev
    environment:
      # General
      - CS_DEV=TRUE
      - CS_DEVCONTAINER=TRUE
      - CS_LOGLEVEL=debug
      # Connection stuff:
      - CS_AP_SSID=${AP_SSID}
      - CS_API_HOST=${API_HOST}
      - CS_API_ADDR=${API_ADDR}
      - CS_API_PORT=${API_PORT}
      # MongoDB credentials:
      - CS_MONGODB_DATABASE=flaskdb
      - CS_MONGODB_USERNAME=flask
      - CS_MONGODB_HOSTNAME=mongodb
      - CS_MONGODB_PASSWORD=${MONGODB_PWD}
      # Flask stuff:
      - CS_DOMAIN=${DOMAIN}
      - FLASK_DEBUG=True
    network_mode: service:mongodb
    command: sleep infinity

  mongodb:
    container_name: ${PROJECT_NAME}-mongodb
    image: ${MONGO_CONTAINER}:${MONGO_VERSION}
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: flask
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null

volumes:
  mongodb-data:
