version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  mongodb:
    container_name: ${PROJECT_NAME}-mongodb
    image: ${MONGO_CONTAINER}:${MONGO_VERSION}
    volumes: # Corresponds with volume at the bottom
      - mongodb-data:/data/db
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: flask
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null

volumes:
  mongodb-data:
