version: '3.8'

services:
  combined:
    container_name: ${PROJECT_NAME}-combined
    restart: unless-stopped
    volumes:
      - ./secret_key.txt:/secret/secret_key.txt:cached
      - ../src/CubeServer-common/cubeserver_common:/code/cubeserver_common:cached
      - ../src/CubeServer-common/requirements.txt:/code/requirements-common.txt:cached
      - ../src/CubeServer-common/tests:/code/tests:cached
      - ../src/CubeServer-api/cubeserver_api:/code/cubeserver_api:cached
      - ../src/CubeServer-api/requirements.txt:/code/requirements-api.txt:cached
      - ../src/CubeServer-app/cubeserver_app:/code/cubeserver_app:cached
      - ../src/CubeServer-app/requirements.txt:/code/requirements-app.txt:cached
    build:
      context: ..
      dockerfile: Docker/CubeServer/Dockerfile
      target: combined-dev
      args:
        CERT_SUBJ: "/C=${COUNTRY}/ST=/L=/O=/OU=/CN=${API_ADDR}/"
        CERT_SUBJALTNAME: "${API_ALT_ADDR}"
        CERT_EXP_DAYS: ${API_CERT_EXP_DAYS}
    environment:
      # MongoDB credentials:
      - MONGODB_DATABASE=flaskdb
      - MONGODB_USERNAME=flask
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_PASSWORD=${MONGODB_PWD}
      # Wrapper packaging stuff:
      - API_WRAPPER_GIT_URL_ARDUINO=${API_WRAPPER_GIT_URL_ARDUINO}
      - API_WRAPPER_ZIP_FILENAME_ARDUINO=${API_WRAPPER_ZIP_FILENAME_ARDUINO}
      - API_WRAPPER_GIT_URL_PYTHON=${API_WRAPPER_GIT_URL_PYTHON}
      - API_WRAPPER_ZIP_FILENAME_PYTHON=${API_WRAPPER_ZIP_FILENAME_PYTHON}
      - API_WRAPPER_GIT_URL_CIRCUITPYTHON=${API_WRAPPER_GIT_URL_CIRCUITPYTHON}
      - API_WRAPPER_ZIP_FILENAME_CIRCUITPYTHON=${API_WRAPPER_ZIP_FILENAME_CIRCUITPYTHON}
      - API_WRAPPER_PEM_FILENAME=${API_WRAPPER_PEM_FILENAME}
      - BEACON_CODE_GIT_URL=${BEACON_CODE_GIT_URL}
      # Flask stuff:
      - SERVER_NAME=${DOMAIN}
      - FLASK_DEBUG=True
    network_mode: service:mongodb
    command: sleep infinity

  mongodb:
    container_name: ${PROJECT_NAME}-mongodb
    image: ${MONGO_CONTAINER}:${MONGO_VERSION}
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: flask
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
  
volumes:
  mongodb-data: